User nobody
Group nogroup
Port 8888
Timeout 600
MaxClients 20
StartServers 2
MinSpareServers 2
MaxSpareServers 5
MaxRequestsPerChild 0
LogLevel Info
Allow 192.168.95.0/24
ConnectPort 443
FilterURLs Off
FilterExtended On
FilterCaseSensitive Off
FilterDefaultDeny Yes
Filter "/etc/tinyproxy/filter"
